/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as oxygenSol from "./Oxygen.sol";
export type { oxygenSol };
import type * as planetEarthSol from "./PlanetEarth.sol";
export type { planetEarthSol };
import type * as testTokenSol from "./TestToken.sol";
export type { testTokenSol };
import type * as gameSol from "./game.sol";
export type { gameSol };
import type * as utils from "./utils";
export type { utils };
export type { ECommerce } from "./ECommerce";
export type { Lock } from "./Lock";
export type { POS } from "./POS";
export type { POSFactory } from "./POSFactory";
