/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as oxygenSol from "./Oxygen.sol";
export type { oxygenSol };
import type * as gameSol from "./game.sol";
export type { gameSol };
export type { Lock } from "./Lock";
export type { POS } from "./POS";
export type { POSFactory } from "./POSFactory";
