/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interface from "./interface";
export type { interface };
import type * as plugin from "./plugin";
export type { plugin };
export type { AppURI } from "./AppURI";
