/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1155Enumerable } from "./IERC1155Enumerable";
export type { IERC1155Supply } from "./IERC1155Supply";
export type { IERC721Enumerable } from "./IERC721Enumerable";
export type { IERC721Supply } from "./IERC721Supply";
