/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC165 } from "./IERC165";
export type { IERC20 } from "./IERC20";
export type { IERC2981 } from "./IERC2981";
