/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as plugin from "./plugin";
export type { plugin };
export type { IAppURI } from "./IAppURI";
export type { IBurnableERC1155 } from "./IBurnableERC1155";
export type { IBurnableERC20 } from "./IBurnableERC20";
export type { IBurnableERC721 } from "./IBurnableERC721";
export type { IDelayedRevealDeprecated } from "./IDelayedRevealDeprecated";
export type { IMintableERC1155 } from "./IMintableERC1155";
export type { IMintableERC20 } from "./IMintableERC20";
export type { IMintableERC721 } from "./IMintableERC721";
