/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DiamondHands } from "./DiamondHands";
export type { ERC1155 } from "./ERC1155";
export type { Tournament } from "./Tournament";
